"""KV store backend protocol."""

from typing import Protocol, runtime_checkable


@runtime_checkable
class KVBackend(Protocol):
    def get(self, namespace: str, key: str) -> str | None: ...
    def set(self, namespace: str, key: str, value: str, ttl_seconds: int | None = None) -> None: ...
    def delete(self, namespace: str, key: str) -> bool: ...
    def list_keys(self, namespace: str, prefix: str = "") -> list[str]: ...
    def list_namespaces(self) -> list[str]: ...
    def get_with_metadata(self, namespace: str, key: str) -> dict | None: ...
