#!/usr/bin/env python3
"""Fetch litellm's model database and regenerate the model registry in provider files.

Usage:
    uv run python scripts/update_model_registry.py
"""

import json
import re
import sys
from pathlib import Path

import httpx

# TODO: Is there a abetter  source for this information?  None of the official apis seem to return their own pricing info or capabilities for the most part
#       ^ maybe openrouter?   Need to verify whether it's the same via openrouter vs direct api calls.
LITELLM_URL = "https://raw.githubusercontent.com/BerriAI/litellm/refs/heads/main/model_prices_and_context_window.json"

PROJECT_ROOT = Path(__file__).parent.parent
PROVIDER_FILES = {
    "openai": PROJECT_ROOT / "tsugite" / "providers" / "openai_compat.py",
    "anthropic": PROJECT_ROOT / "tsugite" / "providers" / "anthropic.py",
}

# litellm_provider value → our provider name
PROVIDER_MAP = {
    "openai": "openai",
    "anthropic": "anthropic",
}

# Models to skip (non-chat, deprecated, bedrock variants, etc.)
SKIP_PREFIXES = (
    "ft:",
    "azure/",
    "bedrock/",
    "vertex_ai/",
    "sagemaker/",
    "text-",
    "tts-",
    "whisper-",
    "dall-e",
    "gpt-image",
    "chatgpt-image",
    "omni-moderation",
    "computer-use-",
    "gpt-realtime",
    "gpt-audio",
    "sora-",
    "codex-",
)

# Reasoning model name patterns (for supports_reasoning flag)
REASONING_PATTERNS = re.compile(r"^(o1|o3|o4)(-mini|-preview|-pro)?")


def fetch_litellm_data() -> dict:
    print(f"Fetching {LITELLM_URL}...")
    resp = httpx.get(LITELLM_URL, timeout=30)
    resp.raise_for_status()
    data = resp.json()
    data.pop("sample_spec", None)
    print(f"  Got {len(data)} entries")
    return data


def should_skip(key: str, entry: dict) -> bool:
    if entry.get("mode") != "chat":
        return True
    if any(key.startswith(p) for p in SKIP_PREFIXES):
        return True
    if "/" in key:
        return True
    return False


def entry_to_model_info(key: str, entry: dict, provider: str) -> str:
    """Convert a litellm entry to a ModelInfo(...) constructor string."""
    max_in = entry.get("max_input_tokens")
    max_out = entry.get("max_output_tokens")
    cost_in = entry.get("input_cost_per_token")
    cost_out = entry.get("output_cost_per_token")
    vision = entry.get("supports_vision", False)
    reasoning = bool(REASONING_PATTERNS.match(key))

    parts = []
    if max_in:
        parts.append(f"max_input_tokens={max_in:_}")
    if max_out:
        parts.append(f"max_output_tokens={max_out:_}")
    if cost_in:
        cpm_in = round(cost_in * 1_000_000, 4)
        parts.append(f"input_cost_per_million={cpm_in}")
    if cost_out:
        cpm_out = round(cost_out * 1_000_000, 4)
        parts.append(f"output_cost_per_million={cpm_out}")
    if vision:
        parts.append("supports_vision=True")
    if reasoning:
        parts.append("supports_reasoning=True")

    return f"ModelInfo({', '.join(parts)})"


def generate_dict_block(provider: str, models: dict[str, str]) -> str:
    """Generate the Python dict literal for a provider's models."""
    lines = []
    for key in sorted(models.keys()):
        lines.append(f'    "{provider}/{key}": {models[key]},')
    return "\n".join(lines)


def replace_generated_block(file_path: Path, provider: str, new_block: str) -> set[str]:
    """Replace the generated models block in a provider file. Returns set of manual model keys found."""
    content = file_path.read_text()

    begin_marker = f"# --- BEGIN GENERATED MODELS ({provider}) --- #"
    end_marker = f"# --- END GENERATED MODELS ({provider}) --- #"

    begin_idx = content.find(begin_marker)
    end_idx = content.find(end_marker)
    if begin_idx == -1 or end_idx == -1:
        print(f"  ERROR: Markers not found in {file_path}")
        sys.exit(1)

    # Find existing manual keys (outside the generated block) for duplicate detection
    before_block = content[:begin_idx]
    after_block = content[end_idx + len(end_marker):]
    manual_keys = set()
    for match in re.finditer(r'"' + re.escape(provider) + r'/([^"]+)"', before_block + after_block):
        manual_keys.add(match.group(1))

    var_name = f"_{provider.upper()}_MODELS"
    replacement = (
        f"{begin_marker}\n"
        f"# Auto-generated by scripts/update_model_registry.py — do not edit manually\n"
        f"# fmt: off\n"
        f"{var_name}: dict[str, ModelInfo] = {{\n"
        f"{new_block}\n"
        f"}}\n"
        f"# fmt: on\n"
        f"{end_marker}"
    )

    new_content = content[:begin_idx] + replacement + content[end_idx + len(end_marker):]
    file_path.write_text(new_content)
    return manual_keys


def main():
    data = fetch_litellm_data()

    # Group by our provider names
    by_provider: dict[str, dict[str, str]] = {p: {} for p in PROVIDER_MAP.values()}

    for key, entry in data.items():
        if should_skip(key, entry):
            continue

        litellm_provider = entry.get("litellm_provider", "")
        our_provider = PROVIDER_MAP.get(litellm_provider)
        if not our_provider:
            continue

        model_info_str = entry_to_model_info(key, entry, our_provider)
        by_provider[our_provider][key] = model_info_str

    # Write to each provider file
    for provider, models in by_provider.items():
        file_path = PROVIDER_FILES.get(provider)
        if not file_path:
            continue

        print(f"\n{provider}: {len(models)} chat models found")

        manual_keys = replace_generated_block(file_path, provider, generate_dict_block(provider, models))

        # Check for duplicates
        dupes = manual_keys & set(models.keys())
        if dupes:
            print(f"  WARNING: {len(dupes)} duplicates with manual entries (manual takes priority at runtime):")
            for d in sorted(dupes):
                print(f"    - {provider}/{d}")

        print(f"  Wrote to {file_path.relative_to(PROJECT_ROOT)}")

    print("\nDone. Run `uv run pytest` to verify.")


if __name__ == "__main__":
    main()
