/**
 * Frozen e2e selector contract. Playwright tests select on these exact values,
 * so you may ADD entries but must NEVER rename or remove one. App readiness is
 * marked by `appReady`; tests drive real DOM interaction + HTTP seeding
 * (no window-global test hooks exist or are needed).
 */
export const TESTID = {
  appReady: 'app-ready',
  authGate: 'auth-gate',
  navRail: 'nav-rail',
  navTab: (view: string) => `nav-${view}`,
  view: (view: string) => `view-${view}`,
  gallery: 'gallery',
  // Shell chrome
  topbar: 'topbar',
  themeSwitch: 'theme-switch',
  paletteTrigger: 'palette-trigger',
  keystrip: 'keystrip',
  /** Spaces switcher in the top bar; its chips are selected by accessible name. */
  spaceBar: 'space-bar',
  /** Rail-footer settings entry; the top bar's phone-width one is separate,
   *  since both are in the DOM at once. */
  settingsTrigger: 'settings-trigger',
  settingsTriggerMobile: 'settings-trigger-mobile',
  settingsDrawer: 'settings-drawer',
  /** Per-provider auto-attach toggle in Settings → Context (keyed by provider). */
  settingsContextAutoattach: (key: string) => `settings-context-autoattach-${key}`,
  skillsDrawer: 'skills-drawer',
  viewHost: 'view-host',
  tokenInput: 'token-input',
  tokenConnect: 'token-connect',
  // Picker (generic searchable-list overlay)
  picker: 'picker',
  pickerOption: (value: string) => `picker-opt-${value}`,
  // Multiplexer
  mux: 'mux',
  muxPane: 'mux-pane',
  muxSwitch: 'mux-switch',
  // Jobs view
  jobsLayout: 'jobs-layout',
  jobsFilter: (key: string) => `jobs-filter-${key}`,
  jobsSearch: 'jobs-search',
  jobsSort: 'jobs-sort',
  jobsNew: 'jobs-new',
  jobsBoard: 'jobs-board',
  jobsColumn: (col: string) => `jobs-col-${col}`,
  jobsTable: 'jobs-table',
  jobsEmpty: 'jobs-empty',
  jobCard: (id: string) => `job-card-${id}`,
  jobRow: (id: string) => `job-row-${id}`,
  jobDrawer: 'job-drawer',
  jobRetry: 'job-retry',
  jobCancel: 'job-cancel',
  jobMarkDone: 'job-mark-done',
  jobDismiss: 'job-dismiss',
  jobLinkChat: 'job-link-chat',
  jobLinkWorker: 'job-link-worker',
  jobLinkVerifier: 'job-link-verifier',
  jobLinkTerminal: 'job-link-terminal',
  jobRetryDrawer: 'job-retry-drawer',
  jobRetryHint: 'job-retry-hint',
  jobRetryModel: 'job-retry-model',
  jobRetrySubmit: 'job-retry-submit',
  jobCancelModal: 'job-cancel-modal',
  newJobDrawer: 'new-job-drawer',
  newJobPrompt: 'new-job-prompt',
  newJobAcAdd: 'new-job-ac-add',
  newJobAgent: 'new-job-agent',
  newJobExecutor: 'new-job-executor',
  newJobPreview: 'new-job-preview',
  newJobSubmit: 'new-job-submit',
  // Activity feed
  activityFeed: 'activity-feed',
  activityFilter: (key: string) => `activity-filter-${key}`,
  activityDay: (key: string) => `activity-day-${key}`,
  activityEntry: (id: string) => `activity-entry-${id}`,
  activityRetry: 'activity-retry',
  // Schedules view
  schedulesNew: 'schedules-new',
  schedulesCleanup: 'schedules-cleanup',
  schedulesTable: 'schedules-table',
  schedulesSortNext: 'schedules-sort-next',
  scheduleRow: (id: string) => `schedule-row-${id}`,
  scheduleToggle: (id: string) => `schedule-toggle-${id}`,
  scheduleRunNow: (id: string) => `schedule-run-${id}`,
  // The drawer's open state is marked by `scheduleForm` on its <form> (the shared
  // <Drawer> root takes no testid); no separate drawer id needed.
  scheduleForm: 'schedule-form',
  scheduleSave: 'schedule-save',
  scheduleDrawerRun: 'schedule-drawer-run',
  scheduleDelete: 'schedule-delete',
  // Plugins registry
  pluginsTable: 'plugins-table',
  pluginRow: (key: string) => `plugin-row-${key}`,
  pluginError: (key: string) => `plugin-error-${key}`,
  pluginsRetry: 'plugins-retry',
  // Plugin UI surfaces
  pluginSurface: 'plugin-surface',
  pluginSurfaceReload: 'plugin-surface-reload',
  pluginSurfaceMissing: 'plugin-surface-missing',
  // Secrets view
  secretsAdd: 'secrets-add',
  // Chats view (three-part surface: rail | conversation | composer)
  chatRail: 'chat-rail',
  chatRailToggle: 'chat-rail-toggle',
  /** Shared phone-drilldown back affordance (chats/terminals/files content headers). */
  phoneBack: 'phone-back',
  chatSearch: 'chat-search',
  chatNewSession: 'chat-new-session',
  chatNeedsYou: 'chat-needs-you',
  chatConversation: 'chat-conversation',
  /** A rendered client-context gutter row (keyed by provider) above a user turn. */
  chatContextRow: (key: string) => `chat-context-row-${key}`,
  chatComposer: 'chat-composer',
  composerFileInput: 'composer-file-input',
  composerCameraInput: 'composer-camera-input',
  /** "Add context" menu trigger, the popover, and each provider row + attached chip. */
  composerContext: 'composer-context',
  composerContextMenu: 'composer-context-menu',
  composerContextOption: (key: string) => `composer-context-opt-${key}`,
  composerContextChip: (key: string) => `composer-context-chip-${key}`,
  composerStagedMore: 'composer-staged-more',
  /** A server provider's choices submenu, and each `{value}` row within it. */
  composerContextSubmenu: 'composer-context-submenu',
  composerContextChoice: (key: string, value: string) => `composer-context-choice-${key}-${value}`,
  chatReadonly: 'chat-readonly',
  chatSessionMenuTrigger: 'chat-session-menu-trigger',
  chatSessionMenu: 'chat-session-menu',
  chatMetaLink: 'chat-meta-link',
  chatRawMetadata: 'chat-raw-metadata',
  chatCompactionBanner: 'chat-compaction-banner',
  chatLoadEarlier: 'chat-load-earlier',
  chatEmpty: 'chat-empty',
  chatLocalEcho: 'chat-local-echo',
  chatModelTrigger: 'chat-model-trigger',
  chatModelPopover: 'chat-model-popover',
  chatModelSearch: 'chat-model-search',
  chatModelOption: (id: string) => `chat-model-opt-${id}`,
  chatEffortSeg: 'chat-effort-seg',
  /** Prominent, always-visible Retry on a failed turn (re-sends the last message). */
  chatRetry: 'chat-retry',
  /** A user turn's attachments: an image thumbnail button, a non-image file chip,
   *  and the full-image lightbox that a thumbnail opens. */
  chatAttachmentImage: 'chat-attachment-image',
  chatAttachmentChip: 'chat-attachment-chip',
  chatAttachmentLightbox: 'chat-attachment-lightbox',
  /** The inline approval-prompt button row (Approve / Deny / Always allow) awaiting a decision. */
  askApproval: 'ask-approval',
  // Files / workspace wiki view
  filesTree: 'files-tree',
  filesSearch: 'files-search',
  filesDoc: 'files-doc',
  filesMeta: 'files-meta',
  filesDirTable: 'files-dirtable',
  filesBacklinks: 'files-backlinks',
  filesAttach: 'files-attach',
  filesPin: 'files-pin',
  filesModeSeg: 'files-mode-seg',
  filesStale: 'files-stale',
  fileNode: (path: string) => `file-node-${path}`,
  // Agents builder view
  agentsRoster: 'agents-roster',
  agentsSearch: 'agents-search',
  agentRow: (name: string) => `agent-row-${name}`,
  agentEditor: 'agent-editor',
  agentModeSeg: 'agent-mode-seg',
  agentSave: 'agent-save',
  agentRun: 'agent-run',
  // Webhooks view
  webhooksNew: 'webhooks-new',
  webhooksTable: 'webhooks-table',
  webhooksLog: 'webhooks-log',
  webhooksCreateForm: 'webhooks-create-form',
  webhooksDeleteConfirm: 'webhooks-delete-confirm',
  webhookRow: (token: string) => `webhook-row-${token}`,
  webhookReveal: (token: string) => `webhook-reveal-${token}`,
  webhookCopy: (token: string) => `webhook-copy-${token}`,
  webhookTest: (token: string) => `webhook-test-${token}`,
  webhookDelete: (token: string) => `webhook-delete-${token}`,
} as const;
