"""Secret store backend protocol."""

from typing import Protocol, runtime_checkable


@runtime_checkable
class SecretBackend(Protocol):
    def get(self, name: str) -> str | None: ...
    def list_names(self) -> list[str]: ...
    def set(self, name: str, value: str) -> None: ...
    def delete(self, name: str) -> bool: ...
